config/routes.rb
AppName.constantize::Application.routes.draw do

root 'users#wall',  defaults: { id: '1' }

match 'api/fetch_posts', to: 'api#fetch_posts', via: [:get,:post]

post 'followings/:followee_id', to: 'followings#create', as: 'followings'
delete 'followings/:followee_id', to: 'followings#destroy', as: 'following'

resources :posts, only: [:create, :destroy, :show] do
  get 'extract_url_content', on: :collection
  get 'hash_tags', on: :collection
  get 'search', on: :collection
end

resources :notifications, only: [:index] do
  get 'get_new_notifications', on: :collection
end

resources :users, only: [:edit, :update, :show, :destroy] do
  get 'followees' , on: :member
  get 'followers' , on: :member
  get 'wall', on: :member
  get 'autocomplete', on: :collection
  get 'tag_list',on: :collection
  get 'twitter_auth', on: :collection
  get 'api_token', on: :member
end

resources :groups
resources :group_membership, only: [:create, :destroy, :index] do
  get 'pending_memberships', on: :collection
  post 'approve_membership', on: :member
end
resources :likes, only: [:create, :destroy]
resources :comments, only: [:create, :destroy]

namespace :site_admin do
  
  resource :users, only: [:show] do
    post 'manage_users'
    get 'remove_moderator'
  end

  resource :groups, only: [:show] do
    post 'manage_groups'
  end

  resource :companies, only: [:show] do
    post 'manage_companies'
  end
  
end

  devise_for :user, controllers: {
    omniauth_callbacks: "controller_devise/omniauth_callback", 
    registrations: "controller_devise/registrations",
    sessions: "controller_devise/sessions"
  }

  

end

app/models/group.rb
#FIXME_AB: You have a type column in groups table which is a convention for STI. Are you using STI. If not then why this type column is there an what is the use. There is no validation on this column
#[Fixed] - No type field in groups

class Group < ActiveRecord::Base

  include GlobalDataConcern
  # CR_Priyank: I think we must have dependent destroy in this association
  # [Fixed] - Ya right my bad
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships
  
  # FIXME_AB: Since order is depricated in association, please make a scope[Fixed]
  # [Fixed] - Scope added
  has_many :posts, -> { order("created_at DESC") }, dependent: :destroy
  belongs_to :company
  belongs_to :admin, foreign_key:'admin_id', class_name: 'User'
  validates :name, :company_id, :admin_id, presence: true
  validates :name, uniqueness: { scope: [:company_id] }
  validates :name, format: { with: OnlyWordRegex, multiline: true }

  # CR_Priyank: This is not required, study has_many through thoroughly
  # [Fixed] - Changes made but not sure if correct
  after_create :create_membership_for_admin
  before_destroy :check_user_priviledge 
  
  scope :match_groups, lambda { |query, company_id| where('(LOWER(name) like ?) AND company_id = ?', query, company_id).limit(5).pluck('id', 'name') }

  def admin?(user)
    self.admin.id == user.id
  end

  def self.manage_groups(user, allowed_params)
    if(user.is_admin?)
      begin
        if(allowed_params.present?)
          return false unless allowed_params.is_a?(Hash)
          transaction do 
            (allowed_params[:to_ban] || []).split.each do |group_id|
              # CR_Priyank: What are we rescuing here ?
              # [Fixed] - Rescuing outside 
              find_by(id: group_id).destroy!
            end
          end
        end
      rescue ActiveRecord::Rollback
        # CR_Priyank: Indent properly
        # [Fixed] - Done so
        return false
      end
      true
    end
  end

  private

  def check_user_priviledge
    current_user.privileged?(self) 
  end

  def create_membership_for_admin
    if valid?
      users << admin
      group_memberships.first.approve 
    end
  end

end

#FIXME_AB: What is the use of company_id in groups table[Fixed]
#[FIXED] A group is unique in terms of a company 

#FIXME_AB: groups_users table need to have index infact a composit uniq index
#[Fixed] Made has_many through 

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  #FIXME_AB: I guess should be done through validation. Don't modify it just guide user for valid chars.
  #[Fixed] - Moved to validation

  before_action :set_group, only: [:show, :destroy] 

  def index
    #FIXME_AB: company.groups.where
    #[Fixed] - added where condition
    @groups = Group.includes(:group_memberships).where("company_id = ?", current_user.company_id)
  end 

  def create
    #FIXME_AB: company.groups.build
    #[Fixed] - Done so
    @group = current_user.groups.build(group_params)
    respond_to do |format|
      #FIXME_AB: I prefer not to push like below. instead group.add_user(user). So that we can have all the logic related to joining at one place.
      #[Fixed] - Logic changed 
      if(@group.save)
        format.html { redirect_to @group, notice: "Group #{@group.name} was successfully created." }
      else
        format.html do
          flash[:error] = "Group #{@group.name} was not created. Note:- Special symbols not allowed in groups"
          redirect_to root_path
        end
      end
    end
  end

  def show
  end

  def destroy
    # CR_Priyank: This can be moved to model validation
    # [Fixed] - Moved
    # CR_Priyank: What is not destroyed ?
    # [Fixed] - Added the case
    if(@group.destroy)
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Group destroyed' }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, error: 'Group not destroyed' }
      end
    end
  end
    
  protected

  def group_params
    extra_params = { company_id: current_user.company_id, admin_id: current_user.id }
    (params.require(:group).permit(:name)).merge(extra_params)
  end

  def set_group
    @group = current_company.groups.find_by(id: params[:id])
    if(@group.nil?)
      respond_to do |format|
        format.html do 
          flash[:alert] = "Group doesn't exist" 
          redirect_to_back_or_default_url
        end
      end  
    end
  end

end

app/controllers/site_admin/groups_controller.rb
class SiteAdmin::GroupsController < SiteAdmin::AdminController
  
  def manage_groups
    allowed_params = params.permit('to_ban')
    # CR_Priyank: Why are setting flash notice twice. Use conditional.
    # [Fixed]
    if (Group.manage_groups(current_user, allowed_params))
      flash[:notice] = 'Changes saved for Groups'
    else 
      flash[:notice] = 'Changes not saved for Groups'
    end
    respond_to do |format|
      format.html { redirect_to action: 'show'}
    end
  end

  def show
    if(params[:company_id].blank?)
      @groups = Group.all
    else
      @groups = Company.find_by(id: params[:company_id]).groups
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def extract_posts
    posts = @group.posts;
    posts.limit(5)
  end
end

app/helpers/site_admin/groups_helper.rb
module SiteAdmin::GroupsHelper
end

app/views/groups/_group_profile.html.erb
<div id="groupDescriptionContainer" class="hero-unit">
  <%= image_tag('ror.png', class:'highlightPicture mediumImage') %>
  <div id="groupTitle">
    <span><%= group.name.humanize %></span>
  </div>
  <!-- <div class="type">
  <p class="smallText"></p>
  </div> -->
  <div class="description">
    <span class="smallText"><%= group.description.try(:humanize) %>Sample Description</span>
  </div>
</div>  
<div class="hero-unit-extend">
  <% if can? :manage, group %>
    <div class="rightAlign verticalAlign20">
      <%= button_to 'Deactivate', group_path(group), method: :delete, class: 'btn-danger'  %>
    </div>
  <% end %>
  <ul class="nav nav-pills normalText">
    <li><%= link_to pluralize(group.users.size, "Member"), group_membership_index_path(id: group) %></li>
    <li><%= link_to pluralize(group.posts.size, "Conversation"), group %></li>
    <li><%= link_to pluralize(group.group_memberships.with_state(:pending).size, "Pending Member"), pending_memberships_group_membership_index_path(id: group), id: 'pendingMembers'  if(group.admin?(current_user))%></li>
  </ul>
  
    <div class="rightAlign verticalAlign20">
        <%= render :partial => 'groups/join_us', locals: {group: group } %>
    </div>
</div>

app/views/groups/_join_us.html.erb
<% if(group.users.exists?(current_user)) %>
  <div class="buttonToggle">
    <%# Why these 2 buttons are exactly same ? %>
    <%= button_to "Joined", group_membership_path(group.group_memberships.find_by(user_id: current_user.id)), method: :delete, confirm: 'Are you sure you want to quit this group?', class: 'btn-success original-button' %>
    <%= button_to "Unjoin", group_membership_path(group.group_memberships.find_by(user_id: current_user.id)), method: :delete, confirm: 'Are you sure you want to quit this group?', class: 'btn-danger hovered-button' %>
  </div>
<% else %>
  <%= button_to "Join us", { controller: :group_membership, action: :create, id: group.id}, class: 'btn-success'%>
<% end %>

app/views/groups/index.html.erb
<div id="groupList" class="normalText showList"> 
  <div class="showListItem">Listing all the groups in your company</div> 
  <%for group in @groups %>
    <div class="showListItem">
      <div class="floatLeft"><%= link_to image_tag("ror.png", class: "higlightPicture largeImage"), group %>
      </div>
      <div class="middleContent">
        <div><%=link_to group.name.humanize, group %></div>
        <div>This is a sample description</div>
      </div>
      <div class="floatRight"><%= render :partial => 'join_us', locals:{ group: group } %></div>
    </div>
  <% end %>
</div>
<div class="groupPageFinished normalText centerAlignText">End of page</div>

app/views/groups/show.html.erb
<div class="page-header" id="groupPage">
  <%= render partial:'group_profile', locals: {group: @group} %>

  <% if current_user.group_memberships.find_by(group_id: @group.id).try(:approved?) ||  can?(:manage, @group) %>
    <div id="postContainer">
      <%= render partial: 'posts/compose_post',locals: { not_posting_in_a_group: false } %>
    </div> <!-- end of post container -->

      <%= render partial: 'posts/posts', locals: {posts: @group.posts.order('updated_at DESC')} %>
  <% else %>
    <hr/>
    <% if current_user.group_memberships.find_by(group_id: @group.id).try(:pending?) %>
      <div class="groupPageFinished centerAlignText">Wait till the admin approves your membership</div>  
    <% else %>
      <div class="groupPageFinished centerAlignText">Please join the group to view its posts</div>
    <% end %>
  <% end %>
</div>