config/routes.rb
AppName.constantize::Application.routes.draw do

root 'users#wall',  defaults: { id: '1' }

match 'api/fetch_posts', to: 'api#fetch_posts', via: [:get,:post]

post 'followings/:followee_id', to: 'followings#create', as: 'followings'
delete 'followings/:followee_id', to: 'followings#destroy', as: 'following'

resources :posts, only: [:create, :destroy, :show] do
  get 'extract_url_content', on: :collection
  get 'hash_tags', on: :collection
  get 'search', on: :collection
end

resources :notifications, only: [:index] do
  get 'get_new_notifications', on: :collection
end

resources :users, only: [:edit, :update, :show, :destroy] do
  get 'followees' , on: :member
  get 'followers' , on: :member
  get 'wall', on: :member
  get 'autocomplete', on: :collection
  get 'tag_list',on: :collection
  get 'twitter_auth', on: :collection
  get 'api_token', on: :member
end

resources :groups
resources :group_membership, only: [:create, :destroy, :index] do
  get 'pending_memberships', on: :collection
  post 'approve_membership', on: :member
end
resources :likes, only: [:create, :destroy]
resources :comments, only: [:create, :destroy]

namespace :site_admin do
  
  resource :users, only: [:show] do
    post 'manage_users'
    get 'remove_moderator'
  end

  resource :groups, only: [:show] do
    post 'manage_groups'
  end

  resource :companies, only: [:show] do
    post 'manage_companies'
  end
  
end

  devise_for :user, controllers: {
    omniauth_callbacks: "controller_devise/omniauth_callback", 
    registrations: "controller_devise/registrations",
    sessions: "controller_devise/sessions"
  }

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  include GlobalDataConcern
  include PublicActivity::Common
  include NotificationConcern
  include TwitterConcern
  belongs_to :user
  belongs_to :group
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :url_parsed_content, dependent: :destroy
  validates :content, :user, presence: true
  scope :extract_posts, lambda { |users, groups, company_id|  where('(posts.user_id in (?) or posts.group_id in (?) or posts.group_id is ?) and users.company_id = ? ', users, groups, nil, company_id ).joins(:user).order('created_at DESC') }
  scope :find_by_hash_tag, lambda { |hash_tag, users| includes(:comments).where('( posts.content like ? or comments.content like ? )and posts.user_id in (?)', '%' + hash_tag + '%', '%' + hash_tag + '%', users).order('posts.updated_at DESC') }
  before_create :in_valid_group?
  after_create :notify_tagged_users
  after_create :do_tweet
  before_destroy :check_user_priviledge

  private

  def check_user_priviledge
    # if user is privileged(admin, moderator or owner) or is the group owner if post belongs to group
    current_user.privileged?(self) || group.try(:admin) == current_user  
  end

  def in_valid_group?
    #remember nil means public group
    if group
      !!group.users.exists?(id: user.id)
    else
      true
    end
  end
  
end


  

#FIXME_AB: validations please[Fixed]
#[Fixed] - Post Content should not be nil , it has user_id and company_id but group_id is optional

#FIXME_AB: Post can belongs to a user or a group. How about making it a polymorphic? 
#[Fixed] - Block belongs to both user and group(or nil for all company)

#FIXME_AB: How can I share a URL or an image like we do it on. Please plan accordingly
#[Fixed] - Added URl Parsed Content

#FIXME_AB: We also can have tagging with posts
#[Fixed] - Added tags

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # CR_Priyank: Why are we expiring fragment on all actions
  # [Fixed]: OOps sorry, only required in create and destroy
  before_action only: [:create, :destroy] { |post| post.expire_fragment('my_posts' + current_user.name) }
  before_action :set_post, only: [:destroy, :show]
  before_action :parse_url, only: [:extract_url_content]

  def create
    @post = current_user.posts.build(post_params)  
    @post.url_parsed_content = URLParsedContent.new(set_parsed_content)  if (params[:post][:extra_content].present?)
    # CR_Priyank: I think "current_user.posts << @post" is not required. We can do @post.create
    # [Fixed] - Using @post.save
    if(@post.save)
      respond_to do |format|
        format.html do 
          flash[:notice] = "Your post was succesful"
          redirect_to_back_or_default_url 
        end
      end
    else
      respond_to do |format|
        format.html do 
          flash[:error] = "Your post failed"
          redirect_to_back_or_default_url 
        end
      end
    end
  end

  def destroy
    # CR_Priyank: This must be moved to model validation
    # [Fixed]
    if @post.destroy
      flash[:notice] = "Post destroyed"
    else
      flash[:error] = "Post not destroyed"
    end
    redirect_to_back_or_default_url
  end

  def show
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def search
    @search_results = ThinkingSphinx.search (params[:query]  || '') + ' ' + current_user.name
  end

  def hash_tags
    # CR_Priyank: Move this query to model scope
    # [Fixed] - Moved 
    @posts = Post.find_by_hash_tag(params[:hash_tag], current_company.users)
  end

  def extract_url_content
    begin
      @doc = Nokogiri::HTML(open(@url))
      respond_to do |format|
        format.js {}
      end
    rescue
      @url = @url.sub('http://', 'https://')
      @doc = Nokogiri::HTML(open(@url))
      respond_to do |format|
        format.js {}
      end
    end
    
  end

  protected


  def set_post
    @post = Post.find_by(id: params[:id])
    if(@post.nil?)
      flash[:alert] = "Post not found"
      redirect_to_back_or_default_url 
    end
  end

  def set_parsed_content
    params[:post][:extra_content].permit!
  end

  def post_params
    params.require(:post).permit(:content, :group_id, :tags)
  end

  def parse_url
    @url = params[:url][0..-2] #remove the space
    @url = 'http://' + @url if(@url[0..3].downcase == 'www.')
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def extract_tags_from_post(tags)
    tags_array = tags.split()
    User.where(id: tags_array)
  end
end

app/views/posts/_compose_post.html.erb
<% not_posting_in_a_group = true if not_posting_in_a_group.nil? %>
<div id="composePost">
  <%= form_tag posts_path, id: 'postForm' do %>

    <div id="composePostContainer">
      <div id="composePostCopy" class="composeTextCopy normalText"></div>
      <%= text_area_tag 'post[content]', '', placeholder: 'Start a conversation...', id: 'composePostContent', class: "normalText", autocomplete: "off" %>
    </div> 

    <div class="composePostContentOptions">
      <div>
        <% if not_posting_in_a_group %> 
          <% groups_array = [['Public', nil]] %>
          <% groups_array += current_user.groups.map { |group| [group.name.humanize, group.id] } %>
          <span> Group </span> 
          <%= select_tag 'post[group_id]', options_for_select(groups_array), class: 'selectBoxSmall', id: "groupSelect" %>
        <% else %>
          <%= hidden_field_tag 'post[group_id]', @group.id  %>
        <% end %>
        <%= submit_tag 'Post',class: 'btn-success postButton' %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<!-- displaying posts -->
<div id="postsContainer">
  <% for post in posts %>
    <div class="normalText posts ">
      <div class="floatLeft postUserImage">
        <%= link_to image_tag(post.user.avatar, class: 'mediumImage'), post.user %>
      </div>
      <div class="postContent largeText">
        <div class="postAuthorContainer"><%= link_to post.user.name, post.user, class: 'postAuthor' %>
          <div class="postTime smallText">
            <%= post.created_at.to_formatted_s(:short) %>
          </div>
          <br/>
        </div>

        <div class="rightAlign verticalAlign20">
          <%= link_to('x', post_path(post), method: :delete) if can?(:manage, post)   %>
        </div>
        
        <div class="postGroupTag rightAlign normalText">
            To <%= post.group.nil? ? 'All Company' : link_to(post.group.name.titleize, post.group) %>
        </div>

        <div>
          <% post.content.gsub!(/#\w+/i) {|hash_tag| link_to hash_tag, hash_tags_posts_path(hash_tag: hash_tag),  class: 'tags'} %>
          <%if !(post.tags.nil?) %>
            <% for user in extract_tags_from_post(post.tags) %>
               <% post.content.gsub!(/#{user.name}/i) {|user_name|  link_to(user_name, user_path(id: user.id), class: 'tags') } %> 
            <% end %>
          <% end %>

          <%= sanitize(post.content.gsub(URLRegex) {|url| "<a href='#{url}'>#{truncate(url, length:60)}</a>" }, tags: %w(a)) %>
        </div>
        <% if !(post.url_parsed_content.nil?) %>
          <% post_extra_content = post.url_parsed_content %>
          <div class = "postExtraContent">
            <% if !post_extra_content.video_id.nil? %>
              <div class = "youtubeVideo">
                <iframe class="youtube-player" type="text/html" width="400" height="300" src="http://www.youtube.com/embed/<%= post_extra_content.video_id %> " allowfullscreen  frameborder="0"></iframe>
              </div>
              <div class="youtubeVideoInfo">
                <%= link_to post_extra_content.title, post_extra_content.url %> 
              </div>
            <% end %>
            
            <% if !post_extra_content.image_url.nil? %>
              <div class = "postMedia floatLeft">
                <%= image_tag(post_extra_content.image_url,class: 'minSizeImage40') %> 
              </div>
              <div class = "postMediaInfo">
                <%= link_to post_extra_content.title, post_extra_content.url %> 
                <br>
                <%= link_to post_extra_content.url, post_extra_content.url, class:'smallText opacity5' %>
              </div>
            <% end %>

            
          </div>
        <% end %>
     
        <div class="postOptions">

          <% if ( (current_user.likes & post.likes).empty? ) %>
            <%= link_to 'Like', likes_path(post_id: post.id, user_id: current_user.id),  method: :post, remote: true  , class: 'postOptionsLink', id: "like_post_#{post.id.to_s}"  %> 
            <% else %>
              <%= link_to 'Unlike', like_path(id: post.likes.find_by(user_id: current_user.id).id, post_id: post.id, user_id: current_user.id),  method: :delete, remote: true, class: 'postOptionsLink', id: "like_post_#{post.id.to_s}"  %> 
          <% end %>

          <%= link_to 'Comment', '', class: 'postOptionsLink postOptionsComment'  %>

          <%= render partial: 'likes/show_likes', locals: {post: post} %>

          <div class="commentsContainer" >
            <%= render partial: 'comments/comments', locals: {post: post} %>
          </div>

        </div>

      </div><!--end of postContent -->
    </div>
  <% end %>
    <div class="PageFinished borderAbove">End of posts</div>
</div>

app/views/posts/extract_url_content.js.erb
if($('#postPreview').length != 1 )
{
  // prepend post preview and cancel button
  $('.composePostContentOptions').prepend('<div id="postPreview"></div><hr> ');
  $('#postPreview').append('<div class="rightAlign" id="removePreviewPost">x</div>');
 
  // if a you tube video
  <% if @url.include?('youtube.com/watch?v=') %>
    
    <% @video_id = @url.split("watch?v=")[1].split("&")[0] %>
    var VIDEO_ID = '<%= @video_id %>'
    
    $('#postPreview').append('<iframe class="youtube-player" type="text/html"'
    + 'width="400" height="300" src="http://www.youtube.com/embed/' +
    VIDEO_ID + '" allowfullscreen frameborder="0"></iframe>')
 
  //if a normal url/image needs to be parsed
  <% else %>

    // if a the url is a image
    <% if /(\.(jpg|png|gif))/ =~ @url%>
       var image = '<%=j @url %>' 
    // normal url parse
    <% else %>
      // extract first displayable image
      <% imageCollection = @doc.css("img")  %>
      <% @imageURL = '' %>
      <% for image in imageCollection  %> 
        <% if !(image.attributes["src"].nil?) %>
          <% @imageURL =  j(image.attributes["src"].try(:value)) %>
          <% break %>
        <% end %>
      <%end%>
      <% @imageURL = (@url + @imageURL) if !(@imageURL.include?('://') || (@imageURL.empty?)) %>
      var image = '<%=j @imageURL %>';    
    <% end %>
    $('#postPreview').append('<div><img class="atMaxLargeImage" src=' + image + '></img></div>')
  <% end %>
  // extract title and url
  var title = '<%= j link_to((@doc.title||''), @url) %>';
  var url = '<%= link_to truncate(@url, length:100), @url,class: "smallText" %>';
  $('#postPreview').append('<div>' + title + '</div><div>' + url + '</div>')

  //append hidden fields in the form corresponding to the extra content
  $('#postForm').append('<input type="hidden" name="post[extra_content][url]" value="<%=j @url%>"/>')
  <% if !(@doc.title.nil?) %>
    $('#postForm').append('<input type="hidden" name="post[extra_content][title]" value="<%=j @doc.title%>"/>')
  <% end %>
  <% if !(@imageURL.nil? || @imageURL.empty?) %>
    $('#postForm').append('<input type="hidden" name="post[extra_content][image_url]" value="<%=j @imageURL%>"/>')
  <% end %>
  <% if !(@video_id.nil?) %>
    $('#postForm').append('<input type="hidden" name="post[extra_content][video_id]" value="<%=j @video_id%>"/>')
  <% end %>
  // remove preview event 
  $('#removePreviewPost').click(function(){
    $('#postPreview').siblings('hr').remove();
    $('#postPreview').remove();
    $('#composePostContent').focus();
  });
} 

app/views/posts/hash_tags.html.erb
<div id="postContainer">
  <%= render partial: 'posts', locals: {posts: @posts } %>
</div>

app/views/posts/search.html.erb
<%= render partial: 'posts', locals: { posts: @search_results } %>

app/views/posts/show.html.erb
<div id="postContainer">
  <%= render partial: 'posts', locals: {posts: [@post] } %>
</div>

app/views/posts/show.js.erb
$('#notificationModalView .modal-body').html('<%= j render partial: "/posts/posts", locals: { posts: [@post] } %>');
// from notification.js to set the taglist
setPostContentBox();