config/routes.rb
AppName.constantize::Application.routes.draw do

root 'users#wall',  defaults: { id: '1' }

match 'api/fetch_posts', to: 'api#fetch_posts', via: [:get,:post]

post 'followings/:followee_id', to: 'followings#create', as: 'followings'
delete 'followings/:followee_id', to: 'followings#destroy', as: 'following'

resources :posts, only: [:create, :destroy, :show] do
  get 'extract_url_content', on: :collection
  get 'hash_tags', on: :collection
  get 'search', on: :collection
end

resources :notifications, only: [:index] do
  get 'get_new_notifications', on: :collection
end

resources :users, only: [:edit, :update, :show, :destroy] do
  get 'followees' , on: :member
  get 'followers' , on: :member
  get 'wall', on: :member
  get 'autocomplete', on: :collection
  get 'tag_list',on: :collection
  get 'twitter_auth', on: :collection
  get 'api_token', on: :member
end

resources :groups
resources :group_membership, only: [:create, :destroy, :index] do
  get 'pending_memberships', on: :collection
  post 'approve_membership', on: :member
end
resources :likes, only: [:create, :destroy]
resources :comments, only: [:create, :destroy]

namespace :site_admin do
  
  resource :users, only: [:show] do
    post 'manage_users'
    get 'remove_moderator'
  end

  resource :groups, only: [:show] do
    post 'manage_groups'
  end

  resource :companies, only: [:show] do
    post 'manage_companies'
  end
  
end

  devise_for :user, controllers: {
    omniauth_callbacks: "controller_devise/omniauth_callback", 
    registrations: "controller_devise/registrations",
    sessions: "controller_devise/sessions"
  }

  

end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  include GlobalDataConcern
  belongs_to :user
  belongs_to :group
  validates :user_id, :group_id, presence: true

  # CR_Priyank: Call before_destroy on if admin.
  # [Fixed] - If condition added
  before_destroy :check_user_privileged
  before_destroy :destroy_group, if: lambda { |group_membership| group_membership.group && group_membership.group.admin_id == group_membership.user.id}

  state_machine initial: :pending do
    state :pending, value: 0
    state :approved, value: 1

    event :approve do
      transition :pending => :approved
    end
  end

  private

  def check_user_privileged
    current_user.privileged?(self) || group.admin == current_user 
  end

  def destroy_group
    # CR_Priyank: I do not see a reason why group and user is taken in variable
    # [Fixed] - bad mistake, removed
    # Avoid callbacks to run as it will create an infinite loop
    group.delete 
  end
end

app/controllers/group_membership_controller.rb
class GroupMembershipController < ApplicationController
# CR_Priyank: Indent properly
# [Fixed]: Indentation taken care of :(
  before_action :set_group, except: [:approve_membership, :destroy]
  before_action :set_membership, only: [:approve_membership, :destroy]

  def index
  end

  def create
    if( GroupMembership.create(group_id: @group.id, user_id: current_user.id) )
      respond_to do |format|
        format.html { redirect_to @group, notice: "Wait for the admin to approve your request" }
      end  
    else
      respond_to do |format|
        # CR_Priyank: Unexpected behaviour notice should be in alert or error flash
        # [Fixed] - Would keep it in mind from now on 
        format.html { redirect_to @group, error: "User #{current_user.firstname} was not added to the group." }
      end
    end
  end

  def destroy
    #FIXME_AB: group.admin?(current_user)
    #[Fixed] - Method added in model
    # CR_Priyank: I am not sure what we are trying to do here.
    # [Fixed] - Sir basically if you quit your own group you delete everything associated with it
    if ( @membership.try(:destroy) )
      if(@membership.user ==  @membership.group.admin)
        flash[:notice] = "You deleted your own group"
      else
        flash[:notice] = "User @membership.user is not a part of the group #{ @membership.group.name.humanize }"
      end
    else
      flash[:error] = "You couldn't unjoin the group due to some reason, Kindly contact the admin of the group" 
    end
    respond_to do |format|
      format.html { redirect_to root_url }
    end  
  end

  def pending_memberships
    # CR_Priyank: eager load user in this query
    # [Fixed] - Eager loaded user data
    @pending_memberships = @group.group_memberships.includes(:user).with_state(:pending)
    # CR_Priyank: We can use collect here.
    # [Fixed] - Using collect
  end

  def approve_membership
    # CR_Priyank: eager load user and group in this query
    # [Fixed] - Eager loaded user data
    # CR_Priyank: I think finding user and group here is not important, we can get them from @membership in views
    # [Fixed] - Removed
    if (@membership.approve)
      respond_to do |format|
        # CR_Priyank: notify user that action is successful
        #[Fixed] - Notice set
        format.js { flash.now[:notice] = "Member approved" }
      end
    else
      flash.now[:error] = "Can't approve due to some fault"
    end
  end

  protected

  def set_group
    @group = Group.find_by(id: params[:id])
    unless (@group)
      flash[:alert] = "Group not found"
      redirect_to_back_or_default_url
    end 
  end

  def set_membership
    @membership  = GroupMembership.includes(:group, :user).find_by(id: params[:id])
    unless (@membership)
      flash[:alert] = "It seems like u are not a member"
      redirect_to_back_or_default_url
    end
  end

end

app/helpers/group_membership_helper.rb
module GroupMembershipHelper
end

app/views/group_membership/_members_list.html.erb
<%for group_membership in group_memberships %>
  <div class="showListItem">
    <div class="floatLeft">
      <%= link_to image_tag(group_membership.user.avatar,width:"50", height: "50", class: "higlightPicture"), group_membership.user  %>
    </div>

    <div class="middleContent">      
      <div><%=link_to group_membership.user.name.humanize, group_membership.user %></div>
      <div>This is a sample description</div>
      <% if group_membership.group.admin == current_user %>
        <div><%= link_to 'Remove from group', group_membership_path(group_membership), method: :delete, class: 'blackButBlueOnHover underLine' %></div> 
      <% end %>
    </div>

    <div class="floatRight">
      <% if(params[:action] == 'pending_memberships') %>
        <%= button_to 'Approve', approve_membership_group_membership_path(group_membership), class: 'btn-success', remote: true %>
      <% else %>
        <%= render :partial => 'users/following_status', locals: { user: group_membership.user } %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/group_membership/approve_membership.js.erb
$('a[href ="<%= user_path(@membership.user)%>"]').closest('.showListItem').remove();
$('#pendingMembers').text('<%= pluralize(@membership.group.group_memberships.with_state(:pending).size, "Pending Member") %>');

app/views/group_membership/index.html.erb
<div class="page-header" id="groupPage">
  <%= render partial:'groups/group_profile', locals: {group: @group} %>
  <div id="memberList" class="normalText showList"> 
    <div class="showListItem">Listing all the members of this group</div> 
    
    <%= render partial: 'members_list', locals: {group_memberships: @group.group_memberships} %>

  </div>
  <div class="groupPageFinished normalText centerAlignText">End of page</div>
</div>

app/views/group_membership/pending_memberships.html.erb
<div class="page-header" id="groupPage">
  <%= render partial:'groups/group_profile', locals: {group: @group} %>
  <div id="memberList" class="normalText showList"> 
    <div class="showListItem">Listing all the members of this group</div> 

    <%= render partial: 'members_list', locals: {group_memberships: @pending_memberships} %>

  </div>
  <div class="groupPageFinished normalText centerAlignText">End of page</div>
</div>